name: mini_project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: 
  url_launcher: ^6.0.20

  cupertino_icons: ^1.0.2
  go_router: ^14.3.0
  provider: ^6.1.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  shared_preferences: ^2.3.2
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
